### ISSUE TITLE
How can I contribute / make further personal map changes ?

### ISSUE THREAD

**Issue by NightHawkFur** [UnitedMel/SA-Community-Map-Fixes#13]
Wich map editor did you guys use? MED cannot access modified files from modloader, so any map change I do to the base game files is overwritten by the mod. If I try to replace the regular files with the modded ones, MED crashes (with a few exceptions)

I tried to add another plattform at the Linden Train station because it makes no sense it only has access to one of the tracks IMO (Market station is another case, but would be way harder to fix). It mostly worked but I can't lower the barbed wire fence here because (my best guess) the mod overwrites that change to the original vegasE.ipl

![train1](https://github.com/UnitedMel/SA-Community-Map-Fixes/assets/83876584/d23b10c6-6e3e-4cdf-a2dd-ca86c1e178ad)
![fence](https://github.com/UnitedMel/SA-Community-Map-Fixes/assets/83876584/daa6c326-bcfc-44fa-ae2d-0c177b43f771)

I like to bring more lifes to these areas and make them more realistic. A few years back I also worked on unity station:
https://www.gtagarage.com/mods/show.php?id=29038

**Comment by UnitedMel** [comment]
You can contribute by using pull request with yours modified files. If you need decompiled ipls from CMF, please, switch to **img** branch and you'll find them there. Upload both compiled and decompiled ones.

MED is really unusable, for me at least. I suggest trying to import map chunks in Blender via DragonFF script instead.

Tools we are using:
[MagicTXD](https://www.gtagarage.com/mods/show.php?id=27862)
[Collision File Editor II](https://www.gtagarage.com/mods/show.php?id=1154)
[Euryopa](http://aap.papnet.eu/gta/utils/librw_bin/euryopa.exe)
[Blender](https://www.blender.org/download/)
[DragonFF for Blender](https://github.com/Parik27/DragonFF)
[2DFX Tool & RW Analyze](https://gtaforums.com/topic/576214-sa-creating-2dfx-for-your-models/)
[Binary IPL Decompiler](https://cdn.discordapp.com/attachments/876774964139810926/1024115133049491506/Binary-DeCompiler.exe)

**Comment by mpPako** [comment]
If Anybody wants to contribute my DMs on Discord are open and you are more than welcome to get in touch with us. Good luck with your edits.
