### ISSUE TITLE
Game not loading at all

### ISSUE THREAD

**Issue by LukaTV939** [UnitedMel/SA-Community-Map-Fixes#18]
When I was following [this guide](https://www.youtube.com/watch?v=hLmorC7ie1I) the mod worked for him, however when I try to load a game It's just stuck like this forever.

![image](https://github.com/UnitedMel/SA-Community-Map-Fixes/assets/55237683/6309061a-12ef-4481-9f32-a671dfb275a8)

The readme.md of this repo does look different than the one in the video so a lot of things have probably changed, but I still don't know what causes to load this much

**Comment by mpPako** [comment]
Hard to diagnose that, is it still a problem?

**Comment by LukaTV939** [comment]
Just installed the mod again and I didn't experience it this time, thought I can't really remember what was exactly causing it because this was 7 months ago
If I get this loading bug again I'll reopen the issue, but for now the game runs fine
