### ISSUE TITLE
Dark house bug

### ISSUE THREAD

**Issue by njdawlk0293** [UnitedMel/SA-Community-Map-Fixes#3]
Found this bugs
![bug3](https://user-images.githubusercontent.com/88573435/193289853-2d51d70d-4840-46a9-bc71-c122bf94627d.png)
![bug5](https://user-images.githubusercontent.com/88573435/193295698-251f4203-e41b-4842-9a91-607ee8f8619a.png)
![bugs6](https://user-images.githubusercontent.com/88573435/193295752-64deadf2-3e33-4d21-9b9c-dd1623290b67.png)
![bug7](https://user-images.githubusercontent.com/88573435/193296233-05e0750e-2d57-41fa-affe-1c9bda9eabb5.png)

**Comment by UnitedMel** [comment]
Fixed
