### ISSUE TITLE
Following a tutorial and I really want this mod to work! 

### ISSUE THREAD

**Issue by Gx0st** [UnitedMel/SA-Community-Map-Fixes#5]
Hey everyone! This is probably due to me and how I am installing the mod. However, I am following the exact tutorial and for him, it worked (at least in the video at the time). [](https://www.youtube.com/watch?v=hLmorC7ie1I&t=939s)

I am linking the video to help the DEVS understand how the plebs like me are installing this and why it isn't working now. I would appreciate any help and advice. I want to see this mod myself.

**Comment by Gx0st** [comment]
https://www.youtube.com/watch?v=hLmorC7ie1I&t=939s

**Comment by Maxim1993271** [comment]
add this mod https://forum.mixmods.com.br/f6-mapas-objetos/t8295-sa-parked-binary-ipl-fixes

**Comment by Maxim1993271** [comment]
great mod everything works
