### ISSUE TITLE
Map bugs found

### ISSUE THREAD

**Issue by niks255** [UnitedMel/SA-Community-Map-Fixes#7]
This is the original game bug

![изображение_2023-01-28_131030001](https://user-images.githubusercontent.com/4942241/215260743-0f7c4e30-d245-4148-9670-2f5e7938c35a.png)
![изображение_2023-01-28_131155775](https://user-images.githubusercontent.com/4942241/215260822-0598eef3-92fd-4fa2-afd5-7523a383b17c.png)

And this is not, I believe
![изображение_2023-01-28_131740113](https://user-images.githubusercontent.com/4942241/215261241-6728696b-bbf3-418e-be6c-02326223dcd9.png)

**Comment by niks255** [comment]
Found another one in the impound garage in LV

![gta_sa_Ix2v5sy4Hw](https://github.com/UnitedMel/SA-Community-Map-Fixes/assets/4942241/345acb8c-3576-45e4-8b01-9d90ec2a0e2a)

**Comment by mpPako** [comment]
Will be fixed in next update.
